Ny times
Henryhaulka/NY-Times pull request #1
Opened 2021-02-16 06:34 UTC by Henryhaulka

2021-02-17 17:20 UTC, MahmoudBakr23 requested changes
# **Changes Required 🛑♻**

<hr>

Hello there, I hope you're doing fine. Great work you've done so far on this project. It's pretty much like the original page. However, there are still a few improvements to make to your project in order to get it complete 😊🙏

- [ ] Please make sure to write a descriptive Pull Request (PR) summary (get a quick refresher from [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- [x] Please make sure to write a descriptive README file (also follow the instructions [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- [x] For best practices. Kindly don't leave any anchor tag (aka ```<a href="#">```) href blank, always put a value in it i.e. "#".
- [x] Your Navigation Bar should be in a fixed position, please re-style that part in your CSS file to match the original page.
- [x] In your CSS file, there is some repeated code. Please follow the DRY rule (Don't Repeat Yourself) It's a very important and common rule that every programmer follows. i.e. Instead of 
```
.section15 a {
  text-decoration: none;
}

.nav-right p a {
  color: black;
  text-decoration: none;
}

section h4 a:hover {
  text-decoration: none;
}
```
You could've done it like this
```
.section15 a,
.nav-right p a,
section h4 a:hover {
  text-decoration: none;
}

.nav-right p a {
  color: black;
}
```

- [ ] I don't know why you've left the left side of the page next to the grid blank! Would you please make it like the original page using grid, float, and flex CSS styling techniques. As well as the footer of the page (I see that you've missed that part as well)
- [ ] Please follow the Git Flow Guidelines and fix your linter errors in order for your PR to pass the Github checks.

<hr>

Kindly do the above changes and submit them for another review.
Good luck and happy coding 👨‍💻💻😊

2021-02-18 18:52 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @Henryhaulka     ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.

---

### **Recommended**

**General**

- [x] You have to write a descriptive Pull Request Message with a descriptive title as well. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.

**Section Specific**

- [x] Navigation bar
-  The navbar needs a bit more work done on it, you are missing the login button, the hamburger icon is too far to the left and you have a space between the top of the page and the navbar. Please compare to the actual site and make the changes.

**Original** |  **Your clone**
------------ | -------------
![Screenshot (73)](https://user-images.githubusercontent.com/49621279/108278551-0f0fe180-7130-11eb-9a6d-374388c02c54.png) | ![Screenshot (86)](https://user-images.githubusercontent.com/49621279/108406182-e858b600-71d6-11eb-8546-f5f1021dc147.png)

- [ ] Footer
-  The footer is just about ready, just reduce the font size used in this section.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-02-18 22:50 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Henry Onu** 
Good job with the improvements for this project :muscle:  :muscle:
Your page really looks like the original :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Don't use inline styles in your HTML file
- [ ] Group selectors with the same style definition. Check out this link: http://www.websiteoptimization.com/speed/tweak/groupsel/
- [ ] Don't overuse ID selectors
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-02-18 22:50 UTC, andresporras3423 commented on index.html
> +                <a href="#" style="font-weight: bold;">
Remove inline styles

2021-02-18 22:50 UTC, andresporras3423 commented on style.css
> +#insider {
Don't overuse ID selectors

2021-02-18 22:50 UTC, andresporras3423 commented on style.css
> +}
Group selectors on lines 36 and 46

2021-02-19 04:52 UTC, SmithVyne commented on index.html
> +                    <a href="#" style="margin-top: 5px;">
Try to avoid using inline styling.

2021-02-19 04:52 UTC, SmithVyne requested changes
### Changes required 🤕 👍 
Hello, you have almost completed this project you just need to make the following additional changes to get it approved:
- [REQUIRED] - Do not use inline styles. Check my comment for the exact line where you did.

Make these changes and submit them for a re-review you should get the project approved this time.

You can also reach out to me on slack, @SmithVyne if you have any other questions.

2021-02-19 14:09 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Henry Onu** 
Good job with the improvement for this project :muscle:  :muscle:
Your project is almost perfect :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [ ] Is a general requirements for HTML/CSS projects to use efficient selectors. Remember the DRY principle (don't repeat yourself). You have more than one instance of several selectors with the same style definition. Please, group selectors wherever possible, check out this link: http://www.websiteoptimization.com/speed/tweak/groupsel/
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-02-19 17:27 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-19 17:43 UTC, merged